### ISSUE TITLE
Unable to import gpg keys unless the keyserver is changed in your home settings

### ISSUE THREAD

**Issue by robzombie91** [Frogging-Family/mingw-on-arch-automator#1]
The default keyserver that arch uses fails to import gpg keys required to compile this package

**Comment by Tk-Glitch** [comment]
Arch has begun offering prebuilts for mingw so I will probably deprecate this tool soon. The gpg issue seems unrelated and more of an AUR issue with the new server.

**Comment by robzombie91** [comment]
ok

**Comment by Tk-Glitch** [comment]
I think it can stay open for a while nonetheless *in case*, and for other users who might face the issue as well in the meantime :)
