### ISSUE TITLE
Add key to readme?

### ISSUE THREAD

**Issue by hk3wxy** [Frogging-Family/mingw-on-arch-automator#4]
Gcc is asking for a key (3AB00996FC26A641) , not sure if the problem is only here 
but i had to add this key manually.

would be worth to add the key on readme as well.

**Comment by Tk-Glitch** [comment]
This tool is deprecated now that Arch has added MinGW packages to community repos (`sudo pacman -S mingw-w64-gcc`). I'll make this explicit.

If you want to build your own toolchain nonetheless, I invite you to use https://github.com/Frogging-Family/mostlyportable-gcc as a replacement for `mingw-on-arch-automator`.
